### ISSUE TITLE
GUI- What is the best way to get the file path?

### ISSUE THREAD

**Issue by hcps-womackcz** [FlyingFalafels/PurpleAmerica_Anand_Shezad_Womack#3]
#2 in order to make our program universal, we need to figure out how to make a default path option so it will run on anyone's computer.Potentially adding some option on the GUI's front end? (maybe later we can condense it into a jar file) @hcps-ananda @hcps-shehzadst

**Comment by hcps-shehzadst** [comment]
There could be some logic that you could make that would insert the file path into the program

**Comment by hcps-ananda** [comment]
Hey guys, I fixed the issue. I just decided to do it and now it works so yeah.
