### ISSUE TITLE
GUI- Theme

### ISSUE THREAD

**Issue by hcps-womackcz** [FlyingFalafels/PurpleAmerica_Anand_Shezad_Womack#4]
We have to change the default theme to "DARCULA." This option looks the best and promotes a better user experience.

**Comment by hcps-ananda** [comment]
Ok so we have to use a specific library for that: https://github.com/jfoenixadmin/JFoenix

**Comment by hcps-womackcz** [comment]
Thanks

**Comment by hcps-ananda** [comment]
Christian, this is you added functionality so you need to figure this out. Can you do this after I submit my pull request tonight?

**Comment by hcps-womackcz** [comment]
Sorry, I have been sick will be done with the GUI by tuesday.
