### ISSUE TITLE
GUI- Picture & Title

### ISSUE THREAD

**Issue by hcps-womackcz** [FlyingFalafels/PurpleAmerica_Anand_Shezad_Womack#5]
The GUI's picture needs to be photoshopped. The white borders around it must be taken away so that it looks sleek with the DARCULA theme. Also to promote a more modern and materialistic design the fonts should be changed.

**Comment by hcps-ananda** [comment]
@hcps-womackcz We need to make sure that the material design API and JavaFX libraries are all calibrated to our needs. Please let me know if you are having issues.

**Comment by hcps-womackcz** [comment]
We need java 1.8. I think you can download it from the software center. I
went to the helpdesk, and they said that due to SOL's they aren't changing
anything as of right now.

**Comment by hcps-ananda** [comment]
@hcps-womackcz So that won't work

**Comment by hcps-womackcz** [comment]
I was going to use Java FXML, but it won't work on our computers because we don't have Java 1.8 or Gradle support, so I re-did the GUI and before I submit a pull request we need to discuss some other elements that could be added.

**Comment by hcps-ananda** [comment]
Actually I found a way to enable 1.8 on our computers. I can show you if you'd like. However, I believe using an API that we know first is priority. So redesign the GUI and make it better first. If we need to discuss something, please let me know.

**Comment by hcps-womackcz** [comment]
The only problem is that we need Gradle to use scene builders with the
Jfoenix library.

**Comment by hcps-womackcz** [comment]
Im making a pull request with the new GUI NOW.
